Need to initialize GLFW earlier, before the first call to window_should_close(). Otherwise get the following exception:
Opti@ROLLAB /d/Software/pyopenvr-official-git/src/samples/glfw (master)
$ python hello_glfw3_controllers.py
Traceback (most recent call last):
  File "hello_glfw3_controllers.py", line 22, in <module>
    glfwApp.run_loop()
  File "d:\Software\pyopenvr-official-git\build\lib\openvr\glframework\glfw_app.py", line 80, in run_loop
    while not glfw.window_should_close(self.window):
  File "d:\Software\Python27-amd64\lib\site-packages\glfw.py",line 998, in window_should_close
    return _glfw.glfwWindowShouldClose(window)
  File "d:\Software\Python27-amd64\lib\site-packages\glfw.py",line 592, in errcheck
    _reraise(exc[1], exc[2])
  File "d:\Software\Python27-amd64\lib\site-packages\glfw.py",line 39, in _reraise
    raise (exception, None, traceback)
glfw.GLFWError: (65537) The GLFW library is not initialized